//==================================================
// This file contains the Excluded objects
// Generated By User: vbhargava
// Format Version: 2
// Date: Sat Dec 27 15:43:16 2025
// ExclMode: default
//==================================================
CHECKSUM: "2970532130 2916432780"
covergroup apb_pkg::apb_scoreboard::apb_slave_cg
	coveritem "CR_PWRITE_PSLVERR"
		bins {{"write"},{"err"}}
	coveritem "CR_PWRITE_PWDATA"
		bins {{"read"},{"Pwdata4","Pwdata3","Pwdata2","Pwdata1"}}
	coveritem "CR_PWRITE_PRDATA"
		bins {{"write"},{"Prdata4","Prdata3","Prdata2","Prdata1"}}
	coveritem "CR_PADDR_PSLVERR"
		bins {{"valid_addr"},{"err"}}
	coveritem "CR_PADDR_PWRITE_PSLVERR"
		bins {{"invalid_addr"},{"read"},{"no_err"}}
		bins {{"invalid_addr"},{"write"},{"err"}}
		bins {{"valid_addr"},{"write","read"},{"err"}}
